<h2>Базовый пример на .then .catch .finally</h2>

<v-code lang="js" title="">
Promise.resolve(1)
    // Promise.resolve вернул "1"
    // => "<em>1</em>"
    <u-code>.then</u-code>(data => console.log(data))
<hr>
    // then ничего не вернул
    <u-code>.then</u-code>(data => {
        // => "<em>undefined</em>"
        console.log(data);
        return 2;
    })
<hr>
    // then вернул "2"
    <u-code>.then</u-code>(data => {
        // => "<em>2</em>"
        console.log(data);
        // возникновение ошибки
        throw new Error('Api Error');
        // не имеет значения что вернули
        return 1;
    })
<hr>
    // skip, потому что предыдущий then бросил ошибку
    <u-code>.then</u-code>(data => console.log('Hello'))
<hr>
    // минуя then попадаем в catch
    <u-code>.catch</u-code>(error => {
        // => "<em>Api Error</em>"
        console.log(error.message);
        return 3;
    })
<hr>
    // catch вернул "3"
    <u-code>.then</u-code>(data => {
        console.log(data); // "3"
        return 4;
    })
<hr>
    // then вернул 4, но finally пропустит его мимо себя
    <u-code>.finally</u-code>(data => { 
        // => "<em>undefined</em>"
        console.log(data);
        return 5;
    })
<hr>
    // из finally вернули "5", но результат берется из предудщего then или catch
    // => "<em>4</em>"
    <u-code>.then</u-code>(data => console.log(data))
</v-code>
