<h2>Исключения</h2>

<h3>Создание исключений</h3>
<pre><code class="js">
var calculate = function(n) {
	if (n>10) {
		throw new Error('n должно быть больше 10');
	}
	return n;
}
calculate(20);
</code></pre>

<h3>Обработка исключений</h3>
<pre><code class="js">
try {
	// инструкции, которые могут бросить исключение
} catch (идентификатор) {
	// инструкции будут выполняться если в try произошло исключение
	// передается выражение (идентификатор), которое было в throw
} finally {
	// инструкции будут выполняться независимо от исключения
}
// catch или finally может отсутствовать
// если ошибка необработана, скрипт не будет выполняться
// если ошибка обработана в catch, скрипт продолжит выполнение
</code></pre>

<pre><code class="js">
var calculate = function(n) {
	if (n>10) {
		throw new Error('n должно быть больше 10');
	}
	return n;
}
try {
	calculate(20);
} catch(e) {
	console.log('Ошибка функции calculate() ' + e.message);
}
</code></pre>
